### ISSUE TITLE
Bumping bug

### ISSUE THREAD

**Issue by PyricDemon** [Theblockbuster1/disboard-auto-bump#12]
I have safe bumping enabled, but it still bumps automatically every 2 hours the time could still have 30 minutes and it just bumps #

**Comment by Theblockbuster1** [comment]
So you're saying, that the time has for example 2:30 hours remaining, and when it reaches 0:30 it will bump anyway?

**Comment by PyricDemon** [comment]
yes

**Comment by Theblockbuster1** [comment]
If you think it will help, but if it's easy to reproduce I can just try it myself when I have time

**Comment by PyricDemon** [comment]
alright

**Comment by PyricDemon** [comment]
![error1](https://user-images.githubusercontent.com/79799834/111019611-58013180-838e-11eb-9cb6-50d65abee447.PNG)
![error2](https://user-images.githubusercontent.com/79799834/111019612-5c2d4f00-838e-11eb-9db5-3ebee3481e7f.PNG)
![error3](https://user-images.githubusercontent.com/79799834/111019614-5f283f80-838e-11eb-8751-219a26e4bff5.PNG)
I also got these errors after downloading it

**Comment by Theblockbuster1** [comment]
That wasn't a fix, I was testing something
