### ISSUE TITLE
file deleted,edited,or moved when i drag the file to extensions

### ISSUE THREAD

**Issue by marioalxndr** [Theblockbuster1/disboard-auto-bump#13]
i tried drag and drop the extracted file when i do, a new tab opens and say FILE_ERR the file has been moved, deleted, or edited. how do i fix this?

**Comment by Theblockbuster1** [comment]
The same thing happened to me when I tried dragging and dropping to install directly from WinRAR. Try extracting the file to a separate folder before dragging and dropping it in. Feel free to reopen the issue the problem persists.
![image](https://user-images.githubusercontent.com/48650812/113568730-ffc5f400-9608-11eb-840c-6a2dccaac277.png)
