### ISSUE TITLE
Won't upload the extenstion

### ISSUE THREAD

**Issue by Unidentifedcow** [Theblockbuster1/disboard-auto-bump#14]
![image](https://user-images.githubusercontent.com/70291205/116800081-d1ceb500-aacb-11eb-92f7-00f94f59d0df.png)

this is what i get

**Comment by Theblockbuster1** [comment]
> 1. Download (or clone) the repository and (if you downloaded) **_extract the folder_** into a directory.

You need to extract the .zip file before you load the extension through Chrome. Be sure to follow [the instructions](https://github.com/Theblockbuster1/disboard-auto-bump#install-instructions-chrome) carefully.

If you are still having this problem feel free to reopen the issue.
