### ISSUE TITLE
Can't bump server when extension is added to chrome

### ISSUE THREAD

**Issue by Pil1** [Theblockbuster1/disboard-auto-bump#19]
Server wouldn't bump, not until I completely removed the extension from chrome, then it worked like normal.

note: when i did have the extention added I could still bump manually using middle mouse click on the normal bump button.

**Comment by Pil1** [comment]
I forgot to mention that the auto bump hasnt been working for almost a day now.

**Comment by Pil1** [comment]
![image](https://user-images.githubusercontent.com/87957044/126931006-55a0ea8f-217a-4582-9414-18be2b2c6f97.png)

**Comment by meerkatsignals** [comment]
Same issue on chrome and ff

**Comment by Theblockbuster1** [comment]
Fixed! (probably)
