### ISSUE TITLE
The "B" to autobump doesnt pop up when the extension is installed

### ISSUE THREAD

**Issue by X64onV3RM** [Theblockbuster1/disboard-auto-bump#20]
When i install the extension it the disboard page stays like normal with no changes
![image](https://user-images.githubusercontent.com/88626626/128638960-c8b672eb-9120-448f-afb4-a69024f173ee.png)

**Comment by Theblockbuster1** [comment]
Are there any errors in `chrome://extensions` or in the DevTools (press F12 on the dashboard)? (assuming you're using Google Chrome)

**Comment by X64onV3RM** [comment]
yes it says this in the console 
![image](https://user-images.githubusercontent.com/88626626/128656820-d9bd0096-f763-4646-abd1-45aff930ae11.png)

**Comment by X64onV3RM** [comment]
![image](https://user-images.githubusercontent.com/88626626/128656853-45406c55-7623-4899-b1e6-f3e92ff988c4.png)

**Comment by Theblockbuster1** [comment]
Very strange, I've never seen this before. Maybe try to reinstall the extension? Also what OS are you using?
Anyway if that doesn't work maybe try to use it without an Antivirus, as it may be blocking the extension. Honestly, I have no idea why this is happening and cannot reproduce.

**Comment by Theblockbuster1** [comment]
Also what does it show when you click here?
![image](https://user-images.githubusercontent.com/48650812/128659786-3f521563-9dbc-4b6b-9ece-7b76bb9f5c27.png)

**Comment by X64onV3RM** [comment]
reinstalling worked thank you :)
