### ISSUE TITLE
Unrecognized manifest key 'browser_specific_settings'.

### ISSUE THREAD

**Issue by NimaWood** [Theblockbuster1/disboard-auto-bump#26]
![Opera Momentaufnahme_2022-07-17_015302_chrome](https://user-images.githubusercontent.com/96501660/179375404-47737d3b-c331-477c-b6b2-26e7c95268d8.png)

**Comment by Theblockbuster1** [comment]
Both of these are just warnings, and can be safely ignored as mentioned in the [FAQ](https://github.com/Theblockbuster1/disboard-auto-bump#faq).
