### ISSUE TITLE
Hi i have these issues

### ISSUE THREAD

**Issue by AngelG1g** [Theblockbuster1/disboard-auto-bump#28]
DO COPY PASTE:     https://user-images.githubusercontent.com/114211550/191901394-70d3f2d8-b29b-4889-a61b-6e73fcc270ee.png
DO COPY PASTE:     https://user-images.githubusercontent.com/114211550/191901397-0dafbc0b-b8c5-40d3-adc0-522e3111231e.png

**Comment by Theblockbuster1** [comment]
These are just warnings and can both be ignored, as mentioned in the [FAQ](https://github.com/Theblockbuster1/disboard-auto-bump#faq).
