### ISSUE TITLE
Error: "Unrecognized manifest key 'browser_specific_settings'."

### ISSUE THREAD

**Issue by Raxader** [Theblockbuster1/disboard-auto-bump#7]
![image](https://user-images.githubusercontent.com/42217808/98060962-cf541100-1e42-11eb-90c0-1cd8575ecfd3.png)
Little bit of an error. Not sure what it means. Chrome version 86.0.4240.111.
I also have that ReferenceError, but I am too lazy to add the double quotes. 😁

**Comment by Theblockbuster1** [comment]
Please read the [FAQ](https://github.com/Theblockbuster1/disboard-auto-bump#faq) before making an issue. Also restarting Chrome might fix the ReferenceError as mentioned [here](https://github.com/Theblockbuster1/disboard-auto-bump/issues/1#issuecomment-650783336).
